# Generated by Django 4.2 on 2024-10-01 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_comment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
    ]
